// Mocks generated by Mockito 5.4.4 from annotations
// in posts/test/TDD_test/unit_test/posts_list/presentation_layer/posts_list_bloc_test_cases/posts_list_bloc_unit_test_cases.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:posts/features/posts_lists/domain_layer/models/post_model.dart'
    as _i5;
import 'package:posts/features/posts_lists/domain_layer/repositories/posts_repository/posts_repository.dart'
    as _i2;
import 'package:posts/features/posts_lists/domain_layer/use_cases/posts_use_case.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeAbstractPostsListRepository_0 extends _i1.SmartFake
    implements _i2.AbstractPostsListRepository {
  _FakeAbstractPostsListRepository_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [PostsListUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockPostsListUseCase extends _i1.Mock implements _i3.PostsListUseCase {
  MockPostsListUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.AbstractPostsListRepository get postsListRepository =>
      (super.noSuchMethod(
        Invocation.getter(#postsListRepository),
        returnValue: _FakeAbstractPostsListRepository_0(
          this,
          Invocation.getter(#postsListRepository),
        ),
      ) as _i2.AbstractPostsListRepository);

  @override
  _i4.Future<List<_i5.PostModel>> call() => (super.noSuchMethod(
        Invocation.method(
          #call,
          [],
        ),
        returnValue: _i4.Future<List<_i5.PostModel>>.value(<_i5.PostModel>[]),
      ) as _i4.Future<List<_i5.PostModel>>);
}
