// Mocks generated by Mockito 5.4.4 from annotations
// in posts/test/TDD_test/unit_test/unit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:http/http.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;
import 'package:posts/data_layer/post_repository/post_api.dart' as _i3;
import 'package:posts/domain_layer/models/generic_model.dart' as _i5;
import 'package:posts/domain_layer/models/post_model.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeClient_0 extends _i1.SmartFake implements _i2.Client {
  _FakeClient_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [PostApi].
///
/// See the documentation for Mockito's code generation for more information.
class MockPostApi extends _i1.Mock implements _i3.PostApi {
  MockPostApi() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Client get client => (super.noSuchMethod(
        Invocation.getter(#client),
        returnValue: _FakeClient_0(
          this,
          Invocation.getter(#client),
        ),
      ) as _i2.Client);

  @override
  _i4.Future<_i5.Result<List<_i6.PostModel>>> getPosts() => (super.noSuchMethod(
        Invocation.method(
          #getPosts,
          [],
        ),
        returnValue: _i4.Future<_i5.Result<List<_i6.PostModel>>>.value(
            _i7.dummyValue<_i5.Result<List<_i6.PostModel>>>(
          this,
          Invocation.method(
            #getPosts,
            [],
          ),
        )),
      ) as _i4.Future<_i5.Result<List<_i6.PostModel>>>);

  @override
  _i4.Future<_i5.Result<_i6.PostModel>> createPost(
    String? title,
    String? subtitle,
    int? userId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #createPost,
          [
            title,
            subtitle,
            userId,
          ],
        ),
        returnValue: _i4.Future<_i5.Result<_i6.PostModel>>.value(
            _i7.dummyValue<_i5.Result<_i6.PostModel>>(
          this,
          Invocation.method(
            #createPost,
            [
              title,
              subtitle,
              userId,
            ],
          ),
        )),
      ) as _i4.Future<_i5.Result<_i6.PostModel>>);
}
